version: '3.8'

services:
  registration:
    build:
      context: .
      dockerfile: services/registration/Dockerfile
      target: development
    volumes:
      - ./services/registration:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    command: pnpm dev

  avs:
    build:
      context: .
      dockerfile: services/avs/Dockerfile
      target: development
    volumes:
      - ./services/avs:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
    command: pnpm dev

  graph:
    build:
      context: .
      dockerfile: services/graph/Dockerfile
      target: development
    volumes:
      - ./services/graph:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
    command: pnpm dev

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      target: development
    volumes:
      - ./apps/frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: pnpm dev

networks:
  default:
    name: motherdao-network
